name: Compile Latex and Release
on: 
  push:
    branches:
      - main
jobs:
  CompileAndRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      pdf-name: dwt-formelsammlung.pdf
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get update and install TeXLive
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
      - name: Prepare PDF
        run: |
          sed -i 's/GITHUB_SERVER_URL/${{ GITHUB_SERVER_URL }}/g' src/main.tex
          sed -i 's/GITHUB_REPOSITORY/${{ GITHUB_REPOSITORY }}/g' src/main.tex
          sed -i 's/GITHUB\\_SHA/test/g' src/main.tex
      - name: Build latex to PDF
        run: |
          mkdir build
          pdflatex -output-directory=. src/main.tex
          mv main.pdf ${{ env.pdf-name }}
      - name: Upload PDF to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: dwt-formellsammlung
          path: ${{ env.pdf-name }}
          if-no-files-found: error
          

