name: Compile Latex and Release
on: 
  pull_request:
    branches:
      - main
jobs:
  CompileAndRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      pdf-name: dwt-formelsammlung.pdf
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get update and install TeXLive
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
      - name: Prepare PDF
        run: |
          sed -i 's/GITHUB_SERVER_URL/${{ env.GITHUB_SERVER_URL }}/g' src/main.tex
          sed -i 's/GITHUB_REPOSITORY/${{ env.GITHUB_REPOSITORY }}/g' src/main.tex
          sed -i 's/GITHUB\\_SHA/${{ env.GITHUB_SHA }}/g' src/main.tex
      - name: Build latex to PDF
        run: |
          mkdir build
          pdflatex -output-directory=. src/main.tex
          mv main.pdf ${{ env.pdf-name }}